import type { Metadata } from "next";
import localFont from "next/font/local";
import BackgroundText from "./backgroundText.tsx"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getJs() {
    console.log((await fetch('/questions')))
    return (await fetch('http://localhost:3000/_next/static/chunks/app-pages-internals.js').body)
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackgroundText />
        <div>
        {children}
        </div>
      </body>
    </html>
  );
}
